### ISSUE TITLE
Current Use Validation for NMBGMR

### ISSUE THREAD

**Issue by jdmattern** [NMWDI/VocabService#2]
The current_use validation fails for NMBGMR because the first letter is capitalized in BQ. 

Ex: 'Unused' whereas the vocab has 'unused'. Therefore, validation fails.

@jirhiker Should we switch all of the first letters to capital letters?

**Comment by jdmattern** [comment]
@jirhiker There is also "inactive_exists_but_not_used", and it is separated out in BQ. Should there be a transformation in the Destination connector to combine with underscore or match the separated words to vocabs like this?

**Comment by jirhiker** [comment]
@jdmattern In general, its the responsibility of the destination connector to map the input data to the output format. So if its "Unused" in the source but the specification calls for "unused" the destination connector needs to do the necessary transformation

**Comment by jirhiker** [comment]
@jdmattern if is "inactive exists but not used" in the source it should be converted to `inactive_exists_but_not_used` by the destination connector

if there is a value that doesn't map to an existing accepted value then we will discuss adding it to the specification
